### ISSUE TITLE
Integration with node js and ionic angular project

### ISSUE THREAD

**Issue by varaprasadreddy9676** [sparkplug/momoapi-node-example#3]
Can you please explain how can I integrate this momo payments for vietnam in my ionic angular mobile application or also any web application.

**Comment by raybesiga** [comment]
Hi @varaprasadreddy9676 the MTN MoMo API only works for the countries in which MTN operates in Africa. It is not the right package for use in Vietnam.

**Comment by varaprasadreddy9676** [comment]
> Hi @varaprasadreddy9676 the MTN MoMo API only works for the countries in which MTN operates in Africa. It is not the right package for use in Vietnam.

Thank you for clarification.

**Comment by raybesiga** [comment]
You are welcome.
